<?php

$ranksetNames["PokemonGenIV"] = "Pokemon Gen IV";

$ranksetData["PokemonGenIV"] = [
array("num" => 0, "image" => '', "text" => 'Non-Poster'),  
array("num" => 1, "image" => '001.png', "text" => 'Breloom'), 
array("num" => 10, "image" => '002.png', "text" => 'Lanturn'),
array("num" => 50, "image" => '003.png', "text" => 'Mr. Mime'),
array("num" => 100, "image" => '004.png', "text" => 'Dodrio'), 
array("num" => 150, "image" => '005.png', "text" => 'Absol'),
array("num" => 250, "image" => '006.png', "text" => 'Stantler'),   
array("num" => 500, "image" => '007.png', "text" => 'Skarmory'),
array("num" => 750, "image" => '008.png', "text" => 'Mantine'), 
array("num" => 1000, "image" => '009.png', "text" => 'Forretress'),                
array("num" => 1100, "image" => '010.png', "text" => 'Magneton'),
array("num" => 1200, "image" => '011.png', "text" => 'Swalot'),
array("num" => 1400, "image" => '012.png', "text" => 'Crawdaunt'),
array("num" => 1600, "image" => '013.png', "text" => 'Whiscash'),
array("num" => 1800, "image" => '014.png', "text" => 'Pidgeot'),
array("num" => 2000, "image" => '015.png', "text" => 'Grumpig'),
array("num" => 2200, "image" => '016.png', "text" => 'Torkoal'),
array("num" => 2400, "image" => '017.png', "text" => 'Xatu'),
array("num" => 2800, "image" => '018.png', "text" => 'Clefable'),
array("num" => 3000, "image" => '019.png', "text" => 'Vespiquen'),
array("num" => 3200, "image" => '020.png', "text" => 'Hariyama'),
array("num" => 3400, "image" => '021.png', "text" => 'Gastrodon'),
array("num" => 3600, "image" => '022.png', "text" => 'Staraptor'),
array("num" => 3800, "image" => '023.png', "text" => 'Cacturne'),
array("num" => 4200, "image" => '024.png', "text" => 'Manectric'),
array("num" => 4400, "image" => '025.png', "text" => 'Kingler'),
array("num" => 4600, "image" => '026.png', "text" => 'Dewgong'),
array("num" => 4800, "image" => '027.png', "text" => 'Raichu'),
array("num" => 5000, "image" => '028.png', "text" => 'Skuntank'),
array("num" => 5200, "image" => '029.png', "text" => 'Phione'),
array("num" => 5400, "image" => '030.png', "text" => 'Froslass'),
array("num" => 5600, "image" => '031.png', "text" => 'Lopunny'),
array("num" => 5800, "image" => '032.png', "text" => 'Glalie'),
array("num" => 6200, "image" => '033.png', "text" => 'Exploud'),
array("num" => 6400, "image" => '034.png', "text" => 'Shiftry'),
array("num" => 6600, "image" => '035.png', "text" => 'Ludicolo'),
array("num" => 6800, "image" => '036.png', "text" => 'Octillery'),
array("num" => 7000, "image" => '182.png', "text" => 'Bellossom'),
array("num" => 7200, "image" => '037.png', "text" => 'Electrode'),
array("num" => 7400, "image" => '038.png', "text" => 'Victreebel'),
array("num" => 7600, "image" => '039.png', "text" => 'Vileplume'),
array("num" => 7800, "image" => '040.png', "text" => 'Ambipom'),
array("num" => 8000, "image" => '041.png', "text" => 'Hypno'),
array("num" => 8200, "image" => '042.png', "text" => 'Spiritomb'),
array("num" => 8400, "image" => '043.png', "text" => 'Relicanth'),

];
// need to do about a few hundred more (http://www.serebii.net/pokedex-dp/stat/all.shtml) <-- the link to website for sprites.
// stopped at Gorebyss