<?php

$ranksetNames["Sonic"] = "Sonic";

$ranksetData["Sonic"] = array(
	array("num" => 0, "image" => '', "text" => 'Non-poster'),
	array("num" => 1, "image" => '', "text" => 'Newcomer'),
	array("num" => 10, "image" => 'sonic.gif', "text" => 'Sonic The Hedgehog'),
	array("num" => 20, "image" => 'tails.gif', "text" => 'Miles "Tails" Prower'),
	array("num" => 30, "image" => 'knuckles.gif', "text" => 'Knukles The Echidna'),
	array("num" => 50, "image" => 'robotnik.gif', "text" => 'Dr. Eggman'),
	array("num" => 75, "image" => 'eggman.gif', "text" => 'Eggman Box'),
	array("num" => 100, "image" => 'ring.gif', "text" => 'Ring'),
	array("num" => 120, "image" => 'ce-blue.png', "text" => 'Blue Time Stone'),
	array("num" => 140, "image" => 'ce-green.png', "text" => 'Green Time Stone'),
	array("num" => 160, "image" => 'ce-grey.png', "text" => 'Grey Time Stone'),
	array("num" => 180, "image" => 'ce-pink.png', "text" => 'Pink Time Stone'),
	array("num" => 200, "image" => 'ce-purple.png', "text" => 'Dark Blue Time Stone'),
	array("num" => 220, "image" => 'ce-red.png', "text" => 'Red Time Stone'),
	array("num" => 300, "image" => 'ce-yellow.png', "text" => 'Yellow Time Stone'),
	array("num" => 325, "image" => 'masteremerald.gif', "text" => 'Master Emerald'),
	array("num" => 350, "image" => 'se-blue.png', "text" => 'Blue Super Emerald'),
	array("num" => 375, "image" => 'se-green.png', "text" => 'Green Super Emerald'),
	array("num" => 400, "image" => 'se-grey.png', "text" => 'Grey Super Emerald'),
	array("num" => 425, "image" => 'se-pink.png', "text" => 'Pink Super Emerald'),
	array("num" => 450, "image" => 'se-purple.png', "text" => 'Purple Super Emerald'),
	array("num" => 475, "image" => 'se-red.png', "text" => 'Red Super Emerald'),
	array("num" => 500, "image" => 'se-yellow.png', "text" => 'Yellow Super Emerald'),
	array("num" => 525, "image" => 'SonicKnucklesEmerald.gif', "text" => 'Sonic and Knuckles'),
	array("num" => 550, "image" => 'metal_sonic.gif', "text" => 'Metal Sonic'),
	array("num" => 575, "image" => 'shadow.gif', "text" => 'Shadow'),
	array("num" => 600, "image" => 'motobug.gif', "text" => 'Motobug'),
	array("num" => 650, "image" => 'cream.gif', "text" => 'Cream The rabbit'),
	array("num" => 700, "image" => 'Cheese.gif', "text" => 'Cheese'),
	array("num" => 800, "image" => 'Amy.gif', "text" => 'Amy'),
	array("num" => 900, "image" => 'Badnik.gif', "text" => 'Crabmeat Badnick'),
	array("num" => 1000, "image" => 'Chaos.gif', "text" => 'Chaos'),
);
